### ISSUE TITLE
Запуск в Docker

### ISSUE THREAD

**Issue by ilshat94** [immisterio/Lampac#40]
Корректно в Docker у меня установился только с доступом контейнера к сети хоста:
```
docker run -it --network host --restart always --name lampac immisterio/lampac

``` 
Все завелось как надо и в Docker.

**Comment by alparo** [comment]
у меня в compose.yaml вот так

`services:
  lampac:
    ports:
      - 9118:9118
    restart: unless-stopped
    container_name: lampac
    image: immisterio/lampac
    networks:
      - proxy-network
    volumes:
      - /media/downloads:/home/dlna
      - ./init.conf:/home/init.conf
networks:
  proxy-network:
    external: true`

proxy-network типа bridge

**Comment by serenitatis** [comment]
Мой compose для запуска лампака:

```
services:
   lampac:
      ports:
         - 9118:9118
      restart: always
      container_name: lampac
      image: immisterio/lampac
      volumes:
         - ./config/init.conf:/home/init.conf
         - ./config/JacRed.conf:/home/module/JacRed.current.conf:ro
         - ./config/manifest.json:/home/module/manifest.json:ro
         - ./config/passwd:/home/passwd:ro
         - ./config/cache:/home/cache
         - ./config/dlna:/home/dlna
```

С ним сохраняются настройки модулей и их активности, работает синхронизация и т.д.
